/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'id' : bigint,
  'content' : string,
  'quoteRequestId' : bigint,
  'timestamp' : bigint,
  'senderType' : SenderType,
}
export interface Quotation {
  'id' : bigint,
  'status' : QuotationStatus,
  'priceAmount' : bigint,
  'quoteRequestId' : bigint,
  'description' : string,
  'validityDate' : bigint,
  'timestamp' : bigint,
}
export type QuotationStatus = { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export interface QuoteRequest {
  'id' : bigint,
  'customerName' : string,
  'status' : Status,
  'customerPhone' : string,
  'deadlineDate' : bigint,
  'message' : string,
  'timestamp' : bigint,
  'customerEmail' : string,
  'servicesNeeded' : string,
}
export type SenderType = { 'admin' : null } |
  { 'customer' : null };
export type Status = { 'pending' : null } |
  { 'completed' : null } |
  { 'accepted' : null } |
  { 'declined' : null } |
  { 'quoted' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptQuotation' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createQuotation' : ActorMethod<[bigint, bigint, string, bigint], bigint>,
  'declineQuotation' : ActorMethod<[bigint], undefined>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllQuotations' : ActorMethod<[], Array<Quotation>>,
  'getAllQuoteRequests' : ActorMethod<[], Array<QuoteRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessagesForQuoteRequest' : ActorMethod<[bigint], Array<Message>>,
  'getQuotation' : ActorMethod<[bigint], [] | [Quotation]>,
  'getQuoteRequest' : ActorMethod<[bigint], [] | [QuoteRequest]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[bigint, SenderType, string], undefined>,
  'submitQuoteRequest' : ActorMethod<
    [string, string, string, string, bigint, string],
    bigint
  >,
  'updateQuoteRequestStatus' : ActorMethod<[bigint, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];