/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SenderType = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'quoteRequestId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'senderType' : SenderType,
});
export const QuotationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const Quotation = IDL.Record({
  'id' : IDL.Nat,
  'status' : QuotationStatus,
  'priceAmount' : IDL.Nat,
  'quoteRequestId' : IDL.Nat,
  'description' : IDL.Text,
  'validityDate' : IDL.Int,
  'timestamp' : IDL.Int,
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
  'quoted' : IDL.Null,
});
export const QuoteRequest = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : Status,
  'customerPhone' : IDL.Text,
  'deadlineDate' : IDL.Int,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'customerEmail' : IDL.Text,
  'servicesNeeded' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptQuotation' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createQuotation' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'declineQuotation' : IDL.Func([IDL.Nat], [], []),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllQuotations' : IDL.Func([], [IDL.Vec(Quotation)], ['query']),
  'getAllQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessagesForQuoteRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getQuotation' : IDL.Func([IDL.Nat], [IDL.Opt(Quotation)], ['query']),
  'getQuoteRequest' : IDL.Func([IDL.Nat], [IDL.Opt(QuoteRequest)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, SenderType, IDL.Text], [], []),
  'submitQuoteRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateQuoteRequestStatus' : IDL.Func([IDL.Nat, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SenderType = IDL.Variant({ 'admin' : IDL.Null, 'customer' : IDL.Null });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'quoteRequestId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'senderType' : SenderType,
  });
  const QuotationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const Quotation = IDL.Record({
    'id' : IDL.Nat,
    'status' : QuotationStatus,
    'priceAmount' : IDL.Nat,
    'quoteRequestId' : IDL.Nat,
    'description' : IDL.Text,
    'validityDate' : IDL.Int,
    'timestamp' : IDL.Int,
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
    'quoted' : IDL.Null,
  });
  const QuoteRequest = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : Status,
    'customerPhone' : IDL.Text,
    'deadlineDate' : IDL.Int,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'customerEmail' : IDL.Text,
    'servicesNeeded' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptQuotation' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createQuotation' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'declineQuotation' : IDL.Func([IDL.Nat], [], []),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllQuotations' : IDL.Func([], [IDL.Vec(Quotation)], ['query']),
    'getAllQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessagesForQuoteRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getQuotation' : IDL.Func([IDL.Nat], [IDL.Opt(Quotation)], ['query']),
    'getQuoteRequest' : IDL.Func([IDL.Nat], [IDL.Opt(QuoteRequest)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, SenderType, IDL.Text], [], []),
    'submitQuoteRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateQuoteRequestStatus' : IDL.Func([IDL.Nat, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };